/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AppTeacherRouteImport } from './routes/_app.teacher'
import { Route as AppStudentRouteImport } from './routes/_app.student'
import { Route as AppParentRouteImport } from './routes/_app.parent'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppTeacherIndexRouteImport } from './routes/_app.teacher.index'
import { Route as AppStudentIndexRouteImport } from './routes/_app.student.index'
import { Route as AppParentIndexRouteImport } from './routes/_app.parent.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppTeacherStudentsRouteImport } from './routes/_app.teacher.students'
import { Route as AppTeacherSettingsRouteImport } from './routes/_app.teacher.settings'
import { Route as AppTeacherReportsRouteImport } from './routes/_app.teacher.reports'
import { Route as AppTeacherMessagesRouteImport } from './routes/_app.teacher.messages'
import { Route as AppTeacherLessonDraftRouteImport } from './routes/_app.teacher.lesson-draft'
import { Route as AppTeacherExamsRouteImport } from './routes/_app.teacher.exams'
import { Route as AppTeacherCalendarRouteImport } from './routes/_app.teacher.calendar'
import { Route as AppTeacherAttendanceRouteImport } from './routes/_app.teacher.attendance'
import { Route as AppTeacherAssignmentsRouteImport } from './routes/_app.teacher.assignments'
import { Route as AppTeacherAiAssistantRouteImport } from './routes/_app.teacher.ai-assistant'
import { Route as AppStudentSettingsRouteImport } from './routes/_app.student.settings'
import { Route as AppStudentProfileRouteImport } from './routes/_app.student.profile'
import { Route as AppStudentNotificationsRouteImport } from './routes/_app.student.notifications'
import { Route as AppStudentNotesRouteImport } from './routes/_app.student.notes'
import { Route as AppStudentLabsRouteImport } from './routes/_app.student.labs'
import { Route as AppStudentExamsRouteImport } from './routes/_app.student.exams'
import { Route as AppStudentCoursesRouteImport } from './routes/_app.student.courses'
import { Route as AppStudentCareerRouteImport } from './routes/_app.student.career'
import { Route as AppStudentAssignmentsRouteImport } from './routes/_app.student.assignments'
import { Route as AppStudentAiTutorRouteImport } from './routes/_app.student.ai-tutor'
import { Route as AppStudentAchievementsRouteImport } from './routes/_app.student.achievements'
import { Route as AppParentSettingsRouteImport } from './routes/_app.parent.settings'
import { Route as AppParentProgressRouteImport } from './routes/_app.parent.progress'
import { Route as AppParentMessagesRouteImport } from './routes/_app.parent.messages'
import { Route as AppParentChildRouteImport } from './routes/_app.parent.child'
import { Route as AppParentAiSuggestionsRouteImport } from './routes/_app.parent.ai-suggestions'
import { Route as AppParentAiReportRouteImport } from './routes/_app.parent.ai-report'
import { Route as AppAdminTeachersRouteImport } from './routes/_app.admin.teachers'
import { Route as AppAdminStudentsRouteImport } from './routes/_app.admin.students'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminReportsRouteImport } from './routes/_app.admin.reports'
import { Route as AppAdminProfileRouteImport } from './routes/_app.admin.profile'
import { Route as AppAdminParentsRouteImport } from './routes/_app.admin.parents'
import { Route as AppAdminClassesRouteImport } from './routes/_app.admin.classes'
import { Route as AppAdminAttendanceRouteImport } from './routes/_app.admin.attendance'
import { Route as AppAdminAnnouncementsRouteImport } from './routes/_app.admin.announcements'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app.admin.analytics'
import { Route as AppStudentExamLessonIdRouteImport } from './routes/_app.student.exam.$lessonId'
import { Route as AppStudentCoursesCourseIdLessonsLessonIdRouteImport } from './routes/_app.student.courses.$courseId.lessons.$lessonId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AppTeacherRoute = AppTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentRoute = AppStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AppRoute,
} as any)
const AppParentRoute = AppParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherIndexRoute = AppTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppStudentIndexRoute = AppStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppParentIndexRoute = AppParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppParentRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTeacherStudentsRoute = AppTeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherSettingsRoute = AppTeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherReportsRoute = AppTeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherMessagesRoute = AppTeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherLessonDraftRoute = AppTeacherLessonDraftRouteImport.update({
  id: '/lesson-draft',
  path: '/lesson-draft',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherExamsRoute = AppTeacherExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherCalendarRoute = AppTeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherAttendanceRoute = AppTeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherAssignmentsRoute = AppTeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherAiAssistantRoute = AppTeacherAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppStudentSettingsRoute = AppStudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentProfileRoute = AppStudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentNotificationsRoute = AppStudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentNotesRoute = AppStudentNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentLabsRoute = AppStudentLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentExamsRoute = AppStudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentCoursesRoute = AppStudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentCareerRoute = AppStudentCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentAssignmentsRoute = AppStudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentAiTutorRoute = AppStudentAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentAchievementsRoute = AppStudentAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppParentSettingsRoute = AppParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppParentRoute,
} as any)
const AppParentProgressRoute = AppParentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppParentRoute,
} as any)
const AppParentMessagesRoute = AppParentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppParentRoute,
} as any)
const AppParentChildRoute = AppParentChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => AppParentRoute,
} as any)
const AppParentAiSuggestionsRoute = AppParentAiSuggestionsRouteImport.update({
  id: '/ai-suggestions',
  path: '/ai-suggestions',
  getParentRoute: () => AppParentRoute,
} as any)
const AppParentAiReportRoute = AppParentAiReportRouteImport.update({
  id: '/ai-report',
  path: '/ai-report',
  getParentRoute: () => AppParentRoute,
} as any)
const AppAdminTeachersRoute = AppAdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminStudentsRoute = AppAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminProfileRoute = AppAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminParentsRoute = AppAdminParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminClassesRoute = AppAdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAttendanceRoute = AppAdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnnouncementsRoute = AppAdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppStudentExamLessonIdRoute = AppStudentExamLessonIdRouteImport.update({
  id: '/exam/$lessonId',
  path: '/exam/$lessonId',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentCoursesCourseIdLessonsLessonIdRoute =
  AppStudentCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/$courseId/lessons/$lessonId',
    path: '/$courseId/lessons/$lessonId',
    getParentRoute: () => AppStudentCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AppAdminRouteWithChildren
  '/parent': typeof AppParentRouteWithChildren
  '/student': typeof AppStudentRouteWithChildren
  '/teacher': typeof AppTeacherRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/announcements': typeof AppAdminAnnouncementsRoute
  '/admin/attendance': typeof AppAdminAttendanceRoute
  '/admin/classes': typeof AppAdminClassesRoute
  '/admin/parents': typeof AppAdminParentsRoute
  '/admin/profile': typeof AppAdminProfileRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/students': typeof AppAdminStudentsRoute
  '/admin/teachers': typeof AppAdminTeachersRoute
  '/parent/ai-report': typeof AppParentAiReportRoute
  '/parent/ai-suggestions': typeof AppParentAiSuggestionsRoute
  '/parent/child': typeof AppParentChildRoute
  '/parent/messages': typeof AppParentMessagesRoute
  '/parent/progress': typeof AppParentProgressRoute
  '/parent/settings': typeof AppParentSettingsRoute
  '/student/achievements': typeof AppStudentAchievementsRoute
  '/student/ai-tutor': typeof AppStudentAiTutorRoute
  '/student/assignments': typeof AppStudentAssignmentsRoute
  '/student/career': typeof AppStudentCareerRoute
  '/student/courses': typeof AppStudentCoursesRouteWithChildren
  '/student/exams': typeof AppStudentExamsRoute
  '/student/labs': typeof AppStudentLabsRoute
  '/student/notes': typeof AppStudentNotesRoute
  '/student/notifications': typeof AppStudentNotificationsRoute
  '/student/profile': typeof AppStudentProfileRoute
  '/student/settings': typeof AppStudentSettingsRoute
  '/teacher/ai-assistant': typeof AppTeacherAiAssistantRoute
  '/teacher/assignments': typeof AppTeacherAssignmentsRoute
  '/teacher/attendance': typeof AppTeacherAttendanceRoute
  '/teacher/calendar': typeof AppTeacherCalendarRoute
  '/teacher/exams': typeof AppTeacherExamsRoute
  '/teacher/lesson-draft': typeof AppTeacherLessonDraftRoute
  '/teacher/messages': typeof AppTeacherMessagesRoute
  '/teacher/reports': typeof AppTeacherReportsRoute
  '/teacher/settings': typeof AppTeacherSettingsRoute
  '/teacher/students': typeof AppTeacherStudentsRoute
  '/admin/': typeof AppAdminIndexRoute
  '/parent/': typeof AppParentIndexRoute
  '/student/': typeof AppStudentIndexRoute
  '/teacher/': typeof AppTeacherIndexRoute
  '/student/exam/$lessonId': typeof AppStudentExamLessonIdRoute
  '/student/courses/$courseId/lessons/$lessonId': typeof AppStudentCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/announcements': typeof AppAdminAnnouncementsRoute
  '/admin/attendance': typeof AppAdminAttendanceRoute
  '/admin/classes': typeof AppAdminClassesRoute
  '/admin/parents': typeof AppAdminParentsRoute
  '/admin/profile': typeof AppAdminProfileRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/students': typeof AppAdminStudentsRoute
  '/admin/teachers': typeof AppAdminTeachersRoute
  '/parent/ai-report': typeof AppParentAiReportRoute
  '/parent/ai-suggestions': typeof AppParentAiSuggestionsRoute
  '/parent/child': typeof AppParentChildRoute
  '/parent/messages': typeof AppParentMessagesRoute
  '/parent/progress': typeof AppParentProgressRoute
  '/parent/settings': typeof AppParentSettingsRoute
  '/student/achievements': typeof AppStudentAchievementsRoute
  '/student/ai-tutor': typeof AppStudentAiTutorRoute
  '/student/assignments': typeof AppStudentAssignmentsRoute
  '/student/career': typeof AppStudentCareerRoute
  '/student/courses': typeof AppStudentCoursesRouteWithChildren
  '/student/exams': typeof AppStudentExamsRoute
  '/student/labs': typeof AppStudentLabsRoute
  '/student/notes': typeof AppStudentNotesRoute
  '/student/notifications': typeof AppStudentNotificationsRoute
  '/student/profile': typeof AppStudentProfileRoute
  '/student/settings': typeof AppStudentSettingsRoute
  '/teacher/ai-assistant': typeof AppTeacherAiAssistantRoute
  '/teacher/assignments': typeof AppTeacherAssignmentsRoute
  '/teacher/attendance': typeof AppTeacherAttendanceRoute
  '/teacher/calendar': typeof AppTeacherCalendarRoute
  '/teacher/exams': typeof AppTeacherExamsRoute
  '/teacher/lesson-draft': typeof AppTeacherLessonDraftRoute
  '/teacher/messages': typeof AppTeacherMessagesRoute
  '/teacher/reports': typeof AppTeacherReportsRoute
  '/teacher/settings': typeof AppTeacherSettingsRoute
  '/teacher/students': typeof AppTeacherStudentsRoute
  '/admin': typeof AppAdminIndexRoute
  '/parent': typeof AppParentIndexRoute
  '/student': typeof AppStudentIndexRoute
  '/teacher': typeof AppTeacherIndexRoute
  '/student/exam/$lessonId': typeof AppStudentExamLessonIdRoute
  '/student/courses/$courseId/lessons/$lessonId': typeof AppStudentCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/parent': typeof AppParentRouteWithChildren
  '/_app/student': typeof AppStudentRouteWithChildren
  '/_app/teacher': typeof AppTeacherRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/announcements': typeof AppAdminAnnouncementsRoute
  '/_app/admin/attendance': typeof AppAdminAttendanceRoute
  '/_app/admin/classes': typeof AppAdminClassesRoute
  '/_app/admin/parents': typeof AppAdminParentsRoute
  '/_app/admin/profile': typeof AppAdminProfileRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/students': typeof AppAdminStudentsRoute
  '/_app/admin/teachers': typeof AppAdminTeachersRoute
  '/_app/parent/ai-report': typeof AppParentAiReportRoute
  '/_app/parent/ai-suggestions': typeof AppParentAiSuggestionsRoute
  '/_app/parent/child': typeof AppParentChildRoute
  '/_app/parent/messages': typeof AppParentMessagesRoute
  '/_app/parent/progress': typeof AppParentProgressRoute
  '/_app/parent/settings': typeof AppParentSettingsRoute
  '/_app/student/achievements': typeof AppStudentAchievementsRoute
  '/_app/student/ai-tutor': typeof AppStudentAiTutorRoute
  '/_app/student/assignments': typeof AppStudentAssignmentsRoute
  '/_app/student/career': typeof AppStudentCareerRoute
  '/_app/student/courses': typeof AppStudentCoursesRouteWithChildren
  '/_app/student/exams': typeof AppStudentExamsRoute
  '/_app/student/labs': typeof AppStudentLabsRoute
  '/_app/student/notes': typeof AppStudentNotesRoute
  '/_app/student/notifications': typeof AppStudentNotificationsRoute
  '/_app/student/profile': typeof AppStudentProfileRoute
  '/_app/student/settings': typeof AppStudentSettingsRoute
  '/_app/teacher/ai-assistant': typeof AppTeacherAiAssistantRoute
  '/_app/teacher/assignments': typeof AppTeacherAssignmentsRoute
  '/_app/teacher/attendance': typeof AppTeacherAttendanceRoute
  '/_app/teacher/calendar': typeof AppTeacherCalendarRoute
  '/_app/teacher/exams': typeof AppTeacherExamsRoute
  '/_app/teacher/lesson-draft': typeof AppTeacherLessonDraftRoute
  '/_app/teacher/messages': typeof AppTeacherMessagesRoute
  '/_app/teacher/reports': typeof AppTeacherReportsRoute
  '/_app/teacher/settings': typeof AppTeacherSettingsRoute
  '/_app/teacher/students': typeof AppTeacherStudentsRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/parent/': typeof AppParentIndexRoute
  '/_app/student/': typeof AppStudentIndexRoute
  '/_app/teacher/': typeof AppTeacherIndexRoute
  '/_app/student/exam/$lessonId': typeof AppStudentExamLessonIdRoute
  '/_app/student/courses/$courseId/lessons/$lessonId': typeof AppStudentCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/parents'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/parent/ai-report'
    | '/parent/ai-suggestions'
    | '/parent/child'
    | '/parent/messages'
    | '/parent/progress'
    | '/parent/settings'
    | '/student/achievements'
    | '/student/ai-tutor'
    | '/student/assignments'
    | '/student/career'
    | '/student/courses'
    | '/student/exams'
    | '/student/labs'
    | '/student/notes'
    | '/student/notifications'
    | '/student/profile'
    | '/student/settings'
    | '/teacher/ai-assistant'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/calendar'
    | '/teacher/exams'
    | '/teacher/lesson-draft'
    | '/teacher/messages'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/students'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/student/exam/$lessonId'
    | '/student/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/parents'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/parent/ai-report'
    | '/parent/ai-suggestions'
    | '/parent/child'
    | '/parent/messages'
    | '/parent/progress'
    | '/parent/settings'
    | '/student/achievements'
    | '/student/ai-tutor'
    | '/student/assignments'
    | '/student/career'
    | '/student/courses'
    | '/student/exams'
    | '/student/labs'
    | '/student/notes'
    | '/student/notifications'
    | '/student/profile'
    | '/student/settings'
    | '/teacher/ai-assistant'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/calendar'
    | '/teacher/exams'
    | '/teacher/lesson-draft'
    | '/teacher/messages'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/students'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/student/exam/$lessonId'
    | '/student/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/parent'
    | '/_app/student'
    | '/_app/teacher'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify'
    | '/_app/admin/analytics'
    | '/_app/admin/announcements'
    | '/_app/admin/attendance'
    | '/_app/admin/classes'
    | '/_app/admin/parents'
    | '/_app/admin/profile'
    | '/_app/admin/reports'
    | '/_app/admin/settings'
    | '/_app/admin/students'
    | '/_app/admin/teachers'
    | '/_app/parent/ai-report'
    | '/_app/parent/ai-suggestions'
    | '/_app/parent/child'
    | '/_app/parent/messages'
    | '/_app/parent/progress'
    | '/_app/parent/settings'
    | '/_app/student/achievements'
    | '/_app/student/ai-tutor'
    | '/_app/student/assignments'
    | '/_app/student/career'
    | '/_app/student/courses'
    | '/_app/student/exams'
    | '/_app/student/labs'
    | '/_app/student/notes'
    | '/_app/student/notifications'
    | '/_app/student/profile'
    | '/_app/student/settings'
    | '/_app/teacher/ai-assistant'
    | '/_app/teacher/assignments'
    | '/_app/teacher/attendance'
    | '/_app/teacher/calendar'
    | '/_app/teacher/exams'
    | '/_app/teacher/lesson-draft'
    | '/_app/teacher/messages'
    | '/_app/teacher/reports'
    | '/_app/teacher/settings'
    | '/_app/teacher/students'
    | '/_app/admin/'
    | '/_app/parent/'
    | '/_app/student/'
    | '/_app/teacher/'
    | '/_app/student/exam/$lessonId'
    | '/_app/student/courses/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/teacher': {
      id: '/_app/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AppTeacherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student': {
      id: '/_app/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AppStudentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent': {
      id: '/_app/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AppParentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher/': {
      id: '/_app/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AppTeacherIndexRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/student/': {
      id: '/_app/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AppStudentIndexRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/parent/': {
      id: '/_app/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AppParentIndexRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/teacher/students': {
      id: '/_app/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof AppTeacherStudentsRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/settings': {
      id: '/_app/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof AppTeacherSettingsRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/reports': {
      id: '/_app/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof AppTeacherReportsRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/messages': {
      id: '/_app/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof AppTeacherMessagesRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/lesson-draft': {
      id: '/_app/teacher/lesson-draft'
      path: '/lesson-draft'
      fullPath: '/teacher/lesson-draft'
      preLoaderRoute: typeof AppTeacherLessonDraftRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/exams': {
      id: '/_app/teacher/exams'
      path: '/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof AppTeacherExamsRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/calendar': {
      id: '/_app/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof AppTeacherCalendarRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/attendance': {
      id: '/_app/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof AppTeacherAttendanceRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/assignments': {
      id: '/_app/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof AppTeacherAssignmentsRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/ai-assistant': {
      id: '/_app/teacher/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/teacher/ai-assistant'
      preLoaderRoute: typeof AppTeacherAiAssistantRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/student/settings': {
      id: '/_app/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof AppStudentSettingsRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/profile': {
      id: '/_app/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AppStudentProfileRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/notifications': {
      id: '/_app/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof AppStudentNotificationsRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/notes': {
      id: '/_app/student/notes'
      path: '/notes'
      fullPath: '/student/notes'
      preLoaderRoute: typeof AppStudentNotesRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/labs': {
      id: '/_app/student/labs'
      path: '/labs'
      fullPath: '/student/labs'
      preLoaderRoute: typeof AppStudentLabsRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/exams': {
      id: '/_app/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof AppStudentExamsRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/courses': {
      id: '/_app/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof AppStudentCoursesRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/career': {
      id: '/_app/student/career'
      path: '/career'
      fullPath: '/student/career'
      preLoaderRoute: typeof AppStudentCareerRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/assignments': {
      id: '/_app/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof AppStudentAssignmentsRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/ai-tutor': {
      id: '/_app/student/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/student/ai-tutor'
      preLoaderRoute: typeof AppStudentAiTutorRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/achievements': {
      id: '/_app/student/achievements'
      path: '/achievements'
      fullPath: '/student/achievements'
      preLoaderRoute: typeof AppStudentAchievementsRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/parent/settings': {
      id: '/_app/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof AppParentSettingsRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/parent/progress': {
      id: '/_app/parent/progress'
      path: '/progress'
      fullPath: '/parent/progress'
      preLoaderRoute: typeof AppParentProgressRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/parent/messages': {
      id: '/_app/parent/messages'
      path: '/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof AppParentMessagesRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/parent/child': {
      id: '/_app/parent/child'
      path: '/child'
      fullPath: '/parent/child'
      preLoaderRoute: typeof AppParentChildRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/parent/ai-suggestions': {
      id: '/_app/parent/ai-suggestions'
      path: '/ai-suggestions'
      fullPath: '/parent/ai-suggestions'
      preLoaderRoute: typeof AppParentAiSuggestionsRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/parent/ai-report': {
      id: '/_app/parent/ai-report'
      path: '/ai-report'
      fullPath: '/parent/ai-report'
      preLoaderRoute: typeof AppParentAiReportRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/admin/teachers': {
      id: '/_app/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AppAdminTeachersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/students': {
      id: '/_app/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AppAdminStudentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/profile': {
      id: '/_app/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AppAdminProfileRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/parents': {
      id: '/_app/admin/parents'
      path: '/parents'
      fullPath: '/admin/parents'
      preLoaderRoute: typeof AppAdminParentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/classes': {
      id: '/_app/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AppAdminClassesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/attendance': {
      id: '/_app/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AppAdminAttendanceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/announcements': {
      id: '/_app/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AppAdminAnnouncementsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/student/exam/$lessonId': {
      id: '/_app/student/exam/$lessonId'
      path: '/exam/$lessonId'
      fullPath: '/student/exam/$lessonId'
      preLoaderRoute: typeof AppStudentExamLessonIdRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/courses/$courseId/lessons/$lessonId': {
      id: '/_app/student/courses/$courseId/lessons/$lessonId'
      path: '/$courseId/lessons/$lessonId'
      fullPath: '/student/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AppStudentCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AppStudentCoursesRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminAnnouncementsRoute: typeof AppAdminAnnouncementsRoute
  AppAdminAttendanceRoute: typeof AppAdminAttendanceRoute
  AppAdminClassesRoute: typeof AppAdminClassesRoute
  AppAdminParentsRoute: typeof AppAdminParentsRoute
  AppAdminProfileRoute: typeof AppAdminProfileRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminStudentsRoute: typeof AppAdminStudentsRoute
  AppAdminTeachersRoute: typeof AppAdminTeachersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminAnnouncementsRoute: AppAdminAnnouncementsRoute,
  AppAdminAttendanceRoute: AppAdminAttendanceRoute,
  AppAdminClassesRoute: AppAdminClassesRoute,
  AppAdminParentsRoute: AppAdminParentsRoute,
  AppAdminProfileRoute: AppAdminProfileRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminStudentsRoute: AppAdminStudentsRoute,
  AppAdminTeachersRoute: AppAdminTeachersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppParentRouteChildren {
  AppParentAiReportRoute: typeof AppParentAiReportRoute
  AppParentAiSuggestionsRoute: typeof AppParentAiSuggestionsRoute
  AppParentChildRoute: typeof AppParentChildRoute
  AppParentMessagesRoute: typeof AppParentMessagesRoute
  AppParentProgressRoute: typeof AppParentProgressRoute
  AppParentSettingsRoute: typeof AppParentSettingsRoute
  AppParentIndexRoute: typeof AppParentIndexRoute
}

const AppParentRouteChildren: AppParentRouteChildren = {
  AppParentAiReportRoute: AppParentAiReportRoute,
  AppParentAiSuggestionsRoute: AppParentAiSuggestionsRoute,
  AppParentChildRoute: AppParentChildRoute,
  AppParentMessagesRoute: AppParentMessagesRoute,
  AppParentProgressRoute: AppParentProgressRoute,
  AppParentSettingsRoute: AppParentSettingsRoute,
  AppParentIndexRoute: AppParentIndexRoute,
}

const AppParentRouteWithChildren = AppParentRoute._addFileChildren(
  AppParentRouteChildren,
)

interface AppStudentCoursesRouteChildren {
  AppStudentCoursesCourseIdLessonsLessonIdRoute: typeof AppStudentCoursesCourseIdLessonsLessonIdRoute
}

const AppStudentCoursesRouteChildren: AppStudentCoursesRouteChildren = {
  AppStudentCoursesCourseIdLessonsLessonIdRoute:
    AppStudentCoursesCourseIdLessonsLessonIdRoute,
}

const AppStudentCoursesRouteWithChildren =
  AppStudentCoursesRoute._addFileChildren(AppStudentCoursesRouteChildren)

interface AppStudentRouteChildren {
  AppStudentAchievementsRoute: typeof AppStudentAchievementsRoute
  AppStudentAiTutorRoute: typeof AppStudentAiTutorRoute
  AppStudentAssignmentsRoute: typeof AppStudentAssignmentsRoute
  AppStudentCareerRoute: typeof AppStudentCareerRoute
  AppStudentCoursesRoute: typeof AppStudentCoursesRouteWithChildren
  AppStudentExamsRoute: typeof AppStudentExamsRoute
  AppStudentLabsRoute: typeof AppStudentLabsRoute
  AppStudentNotesRoute: typeof AppStudentNotesRoute
  AppStudentNotificationsRoute: typeof AppStudentNotificationsRoute
  AppStudentProfileRoute: typeof AppStudentProfileRoute
  AppStudentSettingsRoute: typeof AppStudentSettingsRoute
  AppStudentIndexRoute: typeof AppStudentIndexRoute
  AppStudentExamLessonIdRoute: typeof AppStudentExamLessonIdRoute
}

const AppStudentRouteChildren: AppStudentRouteChildren = {
  AppStudentAchievementsRoute: AppStudentAchievementsRoute,
  AppStudentAiTutorRoute: AppStudentAiTutorRoute,
  AppStudentAssignmentsRoute: AppStudentAssignmentsRoute,
  AppStudentCareerRoute: AppStudentCareerRoute,
  AppStudentCoursesRoute: AppStudentCoursesRouteWithChildren,
  AppStudentExamsRoute: AppStudentExamsRoute,
  AppStudentLabsRoute: AppStudentLabsRoute,
  AppStudentNotesRoute: AppStudentNotesRoute,
  AppStudentNotificationsRoute: AppStudentNotificationsRoute,
  AppStudentProfileRoute: AppStudentProfileRoute,
  AppStudentSettingsRoute: AppStudentSettingsRoute,
  AppStudentIndexRoute: AppStudentIndexRoute,
  AppStudentExamLessonIdRoute: AppStudentExamLessonIdRoute,
}

const AppStudentRouteWithChildren = AppStudentRoute._addFileChildren(
  AppStudentRouteChildren,
)

interface AppTeacherRouteChildren {
  AppTeacherAiAssistantRoute: typeof AppTeacherAiAssistantRoute
  AppTeacherAssignmentsRoute: typeof AppTeacherAssignmentsRoute
  AppTeacherAttendanceRoute: typeof AppTeacherAttendanceRoute
  AppTeacherCalendarRoute: typeof AppTeacherCalendarRoute
  AppTeacherExamsRoute: typeof AppTeacherExamsRoute
  AppTeacherLessonDraftRoute: typeof AppTeacherLessonDraftRoute
  AppTeacherMessagesRoute: typeof AppTeacherMessagesRoute
  AppTeacherReportsRoute: typeof AppTeacherReportsRoute
  AppTeacherSettingsRoute: typeof AppTeacherSettingsRoute
  AppTeacherStudentsRoute: typeof AppTeacherStudentsRoute
  AppTeacherIndexRoute: typeof AppTeacherIndexRoute
}

const AppTeacherRouteChildren: AppTeacherRouteChildren = {
  AppTeacherAiAssistantRoute: AppTeacherAiAssistantRoute,
  AppTeacherAssignmentsRoute: AppTeacherAssignmentsRoute,
  AppTeacherAttendanceRoute: AppTeacherAttendanceRoute,
  AppTeacherCalendarRoute: AppTeacherCalendarRoute,
  AppTeacherExamsRoute: AppTeacherExamsRoute,
  AppTeacherLessonDraftRoute: AppTeacherLessonDraftRoute,
  AppTeacherMessagesRoute: AppTeacherMessagesRoute,
  AppTeacherReportsRoute: AppTeacherReportsRoute,
  AppTeacherSettingsRoute: AppTeacherSettingsRoute,
  AppTeacherStudentsRoute: AppTeacherStudentsRoute,
  AppTeacherIndexRoute: AppTeacherIndexRoute,
}

const AppTeacherRouteWithChildren = AppTeacherRoute._addFileChildren(
  AppTeacherRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppParentRoute: typeof AppParentRouteWithChildren
  AppStudentRoute: typeof AppStudentRouteWithChildren
  AppTeacherRoute: typeof AppTeacherRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppParentRoute: AppParentRouteWithChildren,
  AppStudentRoute: AppStudentRouteWithChildren,
  AppTeacherRoute: AppTeacherRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
