/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AppTeacherRouteImport } from './routes/_app.teacher'
import { Route as AppStudentRouteImport } from './routes/_app.student'
import { Route as AppParentRouteImport } from './routes/_app.parent'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppTeacherIndexRouteImport } from './routes/_app.teacher.index'
import { Route as AppStudentIndexRouteImport } from './routes/_app.student.index'
import { Route as AppParentIndexRouteImport } from './routes/_app.parent.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppStudentYutuqlarRouteImport } from './routes/_app.student.yutuqlar'
import { Route as AppStudentTopshiriqlarRouteImport } from './routes/_app.student.topshiriqlar'
import { Route as AppStudentSozlamalarRouteImport } from './routes/_app.student.sozlamalar'
import { Route as AppStudentProfilRouteImport } from './routes/_app.student.profil'
import { Route as AppStudentLabsRouteImport } from './routes/_app.student.labs'
import { Route as AppStudentKurslarRouteImport } from './routes/_app.student.kurslar'
import { Route as AppStudentKasbiyYolRouteImport } from './routes/_app.student.kasbiy-yol'
import { Route as AppStudentImtihonlarRouteImport } from './routes/_app.student.imtihonlar'
import { Route as AppStudentEslatmalarRouteImport } from './routes/_app.student.eslatmalar'
import { Route as AppStudentBildirishnomalarRouteImport } from './routes/_app.student.bildirishnomalar'
import { Route as AppStudentAiUstozRouteImport } from './routes/_app.student.ai-ustoz'
import { Route as AppStudentImtihonLessonIdRouteImport } from './routes/_app.student.imtihon.$lessonId'
import { Route as AppStudentKurslarCourseIdDarslarLessonIdRouteImport } from './routes/_app.student.kurslar.$courseId.darslar.$lessonId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AppTeacherRoute = AppTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentRoute = AppStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AppRoute,
} as any)
const AppParentRoute = AppParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherIndexRoute = AppTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppStudentIndexRoute = AppStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppParentIndexRoute = AppParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppParentRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppStudentYutuqlarRoute = AppStudentYutuqlarRouteImport.update({
  id: '/yutuqlar',
  path: '/yutuqlar',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentTopshiriqlarRoute = AppStudentTopshiriqlarRouteImport.update({
  id: '/topshiriqlar',
  path: '/topshiriqlar',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentSozlamalarRoute = AppStudentSozlamalarRouteImport.update({
  id: '/sozlamalar',
  path: '/sozlamalar',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentProfilRoute = AppStudentProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentLabsRoute = AppStudentLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentKurslarRoute = AppStudentKurslarRouteImport.update({
  id: '/kurslar',
  path: '/kurslar',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentKasbiyYolRoute = AppStudentKasbiyYolRouteImport.update({
  id: '/kasbiy-yol',
  path: '/kasbiy-yol',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentImtihonlarRoute = AppStudentImtihonlarRouteImport.update({
  id: '/imtihonlar',
  path: '/imtihonlar',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentEslatmalarRoute = AppStudentEslatmalarRouteImport.update({
  id: '/eslatmalar',
  path: '/eslatmalar',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentBildirishnomalarRoute =
  AppStudentBildirishnomalarRouteImport.update({
    id: '/bildirishnomalar',
    path: '/bildirishnomalar',
    getParentRoute: () => AppStudentRoute,
  } as any)
const AppStudentAiUstozRoute = AppStudentAiUstozRouteImport.update({
  id: '/ai-ustoz',
  path: '/ai-ustoz',
  getParentRoute: () => AppStudentRoute,
} as any)
const AppStudentImtihonLessonIdRoute =
  AppStudentImtihonLessonIdRouteImport.update({
    id: '/imtihon/$lessonId',
    path: '/imtihon/$lessonId',
    getParentRoute: () => AppStudentRoute,
  } as any)
const AppStudentKurslarCourseIdDarslarLessonIdRoute =
  AppStudentKurslarCourseIdDarslarLessonIdRouteImport.update({
    id: '/$courseId/darslar/$lessonId',
    path: '/$courseId/darslar/$lessonId',
    getParentRoute: () => AppStudentKurslarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AppAdminRouteWithChildren
  '/parent': typeof AppParentRouteWithChildren
  '/student': typeof AppStudentRouteWithChildren
  '/teacher': typeof AppTeacherRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/student/ai-ustoz': typeof AppStudentAiUstozRoute
  '/student/bildirishnomalar': typeof AppStudentBildirishnomalarRoute
  '/student/eslatmalar': typeof AppStudentEslatmalarRoute
  '/student/imtihonlar': typeof AppStudentImtihonlarRoute
  '/student/kasbiy-yol': typeof AppStudentKasbiyYolRoute
  '/student/kurslar': typeof AppStudentKurslarRouteWithChildren
  '/student/labs': typeof AppStudentLabsRoute
  '/student/profil': typeof AppStudentProfilRoute
  '/student/sozlamalar': typeof AppStudentSozlamalarRoute
  '/student/topshiriqlar': typeof AppStudentTopshiriqlarRoute
  '/student/yutuqlar': typeof AppStudentYutuqlarRoute
  '/admin/': typeof AppAdminIndexRoute
  '/parent/': typeof AppParentIndexRoute
  '/student/': typeof AppStudentIndexRoute
  '/teacher/': typeof AppTeacherIndexRoute
  '/student/imtihon/$lessonId': typeof AppStudentImtihonLessonIdRoute
  '/student/kurslar/$courseId/darslar/$lessonId': typeof AppStudentKurslarCourseIdDarslarLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/student/ai-ustoz': typeof AppStudentAiUstozRoute
  '/student/bildirishnomalar': typeof AppStudentBildirishnomalarRoute
  '/student/eslatmalar': typeof AppStudentEslatmalarRoute
  '/student/imtihonlar': typeof AppStudentImtihonlarRoute
  '/student/kasbiy-yol': typeof AppStudentKasbiyYolRoute
  '/student/kurslar': typeof AppStudentKurslarRouteWithChildren
  '/student/labs': typeof AppStudentLabsRoute
  '/student/profil': typeof AppStudentProfilRoute
  '/student/sozlamalar': typeof AppStudentSozlamalarRoute
  '/student/topshiriqlar': typeof AppStudentTopshiriqlarRoute
  '/student/yutuqlar': typeof AppStudentYutuqlarRoute
  '/admin': typeof AppAdminIndexRoute
  '/parent': typeof AppParentIndexRoute
  '/student': typeof AppStudentIndexRoute
  '/teacher': typeof AppTeacherIndexRoute
  '/student/imtihon/$lessonId': typeof AppStudentImtihonLessonIdRoute
  '/student/kurslar/$courseId/darslar/$lessonId': typeof AppStudentKurslarCourseIdDarslarLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/parent': typeof AppParentRouteWithChildren
  '/_app/student': typeof AppStudentRouteWithChildren
  '/_app/teacher': typeof AppTeacherRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_app/student/ai-ustoz': typeof AppStudentAiUstozRoute
  '/_app/student/bildirishnomalar': typeof AppStudentBildirishnomalarRoute
  '/_app/student/eslatmalar': typeof AppStudentEslatmalarRoute
  '/_app/student/imtihonlar': typeof AppStudentImtihonlarRoute
  '/_app/student/kasbiy-yol': typeof AppStudentKasbiyYolRoute
  '/_app/student/kurslar': typeof AppStudentKurslarRouteWithChildren
  '/_app/student/labs': typeof AppStudentLabsRoute
  '/_app/student/profil': typeof AppStudentProfilRoute
  '/_app/student/sozlamalar': typeof AppStudentSozlamalarRoute
  '/_app/student/topshiriqlar': typeof AppStudentTopshiriqlarRoute
  '/_app/student/yutuqlar': typeof AppStudentYutuqlarRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/parent/': typeof AppParentIndexRoute
  '/_app/student/': typeof AppStudentIndexRoute
  '/_app/teacher/': typeof AppTeacherIndexRoute
  '/_app/student/imtihon/$lessonId': typeof AppStudentImtihonLessonIdRoute
  '/_app/student/kurslar/$courseId/darslar/$lessonId': typeof AppStudentKurslarCourseIdDarslarLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
    | '/student/ai-ustoz'
    | '/student/bildirishnomalar'
    | '/student/eslatmalar'
    | '/student/imtihonlar'
    | '/student/kasbiy-yol'
    | '/student/kurslar'
    | '/student/labs'
    | '/student/profil'
    | '/student/sozlamalar'
    | '/student/topshiriqlar'
    | '/student/yutuqlar'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/student/imtihon/$lessonId'
    | '/student/kurslar/$courseId/darslar/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
    | '/student/ai-ustoz'
    | '/student/bildirishnomalar'
    | '/student/eslatmalar'
    | '/student/imtihonlar'
    | '/student/kasbiy-yol'
    | '/student/kurslar'
    | '/student/labs'
    | '/student/profil'
    | '/student/sozlamalar'
    | '/student/topshiriqlar'
    | '/student/yutuqlar'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/student/imtihon/$lessonId'
    | '/student/kurslar/$courseId/darslar/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/parent'
    | '/_app/student'
    | '/_app/teacher'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
    | '/_app/student/ai-ustoz'
    | '/_app/student/bildirishnomalar'
    | '/_app/student/eslatmalar'
    | '/_app/student/imtihonlar'
    | '/_app/student/kasbiy-yol'
    | '/_app/student/kurslar'
    | '/_app/student/labs'
    | '/_app/student/profil'
    | '/_app/student/sozlamalar'
    | '/_app/student/topshiriqlar'
    | '/_app/student/yutuqlar'
    | '/_app/admin/'
    | '/_app/parent/'
    | '/_app/student/'
    | '/_app/teacher/'
    | '/_app/student/imtihon/$lessonId'
    | '/_app/student/kurslar/$courseId/darslar/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/teacher': {
      id: '/_app/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AppTeacherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student': {
      id: '/_app/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AppStudentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent': {
      id: '/_app/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AppParentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher/': {
      id: '/_app/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AppTeacherIndexRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/student/': {
      id: '/_app/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AppStudentIndexRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/parent/': {
      id: '/_app/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AppParentIndexRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/student/yutuqlar': {
      id: '/_app/student/yutuqlar'
      path: '/yutuqlar'
      fullPath: '/student/yutuqlar'
      preLoaderRoute: typeof AppStudentYutuqlarRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/topshiriqlar': {
      id: '/_app/student/topshiriqlar'
      path: '/topshiriqlar'
      fullPath: '/student/topshiriqlar'
      preLoaderRoute: typeof AppStudentTopshiriqlarRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/sozlamalar': {
      id: '/_app/student/sozlamalar'
      path: '/sozlamalar'
      fullPath: '/student/sozlamalar'
      preLoaderRoute: typeof AppStudentSozlamalarRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/profil': {
      id: '/_app/student/profil'
      path: '/profil'
      fullPath: '/student/profil'
      preLoaderRoute: typeof AppStudentProfilRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/labs': {
      id: '/_app/student/labs'
      path: '/labs'
      fullPath: '/student/labs'
      preLoaderRoute: typeof AppStudentLabsRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/kurslar': {
      id: '/_app/student/kurslar'
      path: '/kurslar'
      fullPath: '/student/kurslar'
      preLoaderRoute: typeof AppStudentKurslarRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/kasbiy-yol': {
      id: '/_app/student/kasbiy-yol'
      path: '/kasbiy-yol'
      fullPath: '/student/kasbiy-yol'
      preLoaderRoute: typeof AppStudentKasbiyYolRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/imtihonlar': {
      id: '/_app/student/imtihonlar'
      path: '/imtihonlar'
      fullPath: '/student/imtihonlar'
      preLoaderRoute: typeof AppStudentImtihonlarRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/eslatmalar': {
      id: '/_app/student/eslatmalar'
      path: '/eslatmalar'
      fullPath: '/student/eslatmalar'
      preLoaderRoute: typeof AppStudentEslatmalarRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/ai-ustoz': {
      id: '/_app/student/ai-ustoz'
      path: '/ai-ustoz'
      fullPath: '/student/ai-ustoz'
      preLoaderRoute: typeof AppStudentAiUstozRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/bildirishnomalar': {
      id: '/_app/student/bildirishnomalar'
      path: '/bildirishnomalar'
      fullPath: '/student/bildirishnomalar'
      preLoaderRoute: typeof AppStudentBildirishnomalarRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/imtihon/$lessonId': {
      id: '/_app/student/imtihon/$lessonId'
      path: '/imtihon/$lessonId'
      fullPath: '/student/imtihon/$lessonId'
      preLoaderRoute: typeof AppStudentImtihonLessonIdRouteImport
      parentRoute: typeof AppStudentRoute
    }
    '/_app/student/kurslar/$courseId/darslar/$lessonId': {
      id: '/_app/student/kurslar/$courseId/darslar/$lessonId'
      path: '/$courseId/darslar/$lessonId'
      fullPath: '/student/kurslar/$courseId/darslar/$lessonId'
      preLoaderRoute: typeof AppStudentKurslarCourseIdDarslarLessonIdRouteImport
      parentRoute: typeof AppStudentKurslarRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppParentRouteChildren {
  AppParentIndexRoute: typeof AppParentIndexRoute
}

const AppParentRouteChildren: AppParentRouteChildren = {
  AppParentIndexRoute: AppParentIndexRoute,
}

const AppParentRouteWithChildren = AppParentRoute._addFileChildren(
  AppParentRouteChildren,
)

interface AppStudentKurslarRouteChildren {
  AppStudentKurslarCourseIdDarslarLessonIdRoute: typeof AppStudentKurslarCourseIdDarslarLessonIdRoute
}

const AppStudentKurslarRouteChildren: AppStudentKurslarRouteChildren = {
  AppStudentKurslarCourseIdDarslarLessonIdRoute:
    AppStudentKurslarCourseIdDarslarLessonIdRoute,
}

const AppStudentKurslarRouteWithChildren =
  AppStudentKurslarRoute._addFileChildren(AppStudentKurslarRouteChildren)

interface AppStudentRouteChildren {
  AppStudentAiUstozRoute: typeof AppStudentAiUstozRoute
  AppStudentBildirishnomalarRoute: typeof AppStudentBildirishnomalarRoute
  AppStudentEslatmalarRoute: typeof AppStudentEslatmalarRoute
  AppStudentImtihonlarRoute: typeof AppStudentImtihonlarRoute
  AppStudentKasbiyYolRoute: typeof AppStudentKasbiyYolRoute
  AppStudentKurslarRoute: typeof AppStudentKurslarRouteWithChildren
  AppStudentLabsRoute: typeof AppStudentLabsRoute
  AppStudentProfilRoute: typeof AppStudentProfilRoute
  AppStudentSozlamalarRoute: typeof AppStudentSozlamalarRoute
  AppStudentTopshiriqlarRoute: typeof AppStudentTopshiriqlarRoute
  AppStudentYutuqlarRoute: typeof AppStudentYutuqlarRoute
  AppStudentIndexRoute: typeof AppStudentIndexRoute
  AppStudentImtihonLessonIdRoute: typeof AppStudentImtihonLessonIdRoute
}

const AppStudentRouteChildren: AppStudentRouteChildren = {
  AppStudentAiUstozRoute: AppStudentAiUstozRoute,
  AppStudentBildirishnomalarRoute: AppStudentBildirishnomalarRoute,
  AppStudentEslatmalarRoute: AppStudentEslatmalarRoute,
  AppStudentImtihonlarRoute: AppStudentImtihonlarRoute,
  AppStudentKasbiyYolRoute: AppStudentKasbiyYolRoute,
  AppStudentKurslarRoute: AppStudentKurslarRouteWithChildren,
  AppStudentLabsRoute: AppStudentLabsRoute,
  AppStudentProfilRoute: AppStudentProfilRoute,
  AppStudentSozlamalarRoute: AppStudentSozlamalarRoute,
  AppStudentTopshiriqlarRoute: AppStudentTopshiriqlarRoute,
  AppStudentYutuqlarRoute: AppStudentYutuqlarRoute,
  AppStudentIndexRoute: AppStudentIndexRoute,
  AppStudentImtihonLessonIdRoute: AppStudentImtihonLessonIdRoute,
}

const AppStudentRouteWithChildren = AppStudentRoute._addFileChildren(
  AppStudentRouteChildren,
)

interface AppTeacherRouteChildren {
  AppTeacherIndexRoute: typeof AppTeacherIndexRoute
}

const AppTeacherRouteChildren: AppTeacherRouteChildren = {
  AppTeacherIndexRoute: AppTeacherIndexRoute,
}

const AppTeacherRouteWithChildren = AppTeacherRoute._addFileChildren(
  AppTeacherRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppParentRoute: typeof AppParentRouteWithChildren
  AppStudentRoute: typeof AppStudentRouteWithChildren
  AppTeacherRoute: typeof AppTeacherRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppParentRoute: AppParentRouteWithChildren,
  AppStudentRoute: AppStudentRouteWithChildren,
  AppTeacherRoute: AppTeacherRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
