ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email_notif   BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS push_notif    BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS weekly_report BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS ai_tips       BOOLEAN NOT NULL DEFAULT TRUE;
